import java.util.list;

public class Q2 {

    public static void main(String[] args) {
        int n1
        int n2

        Scanner scanner = new Scanner(System.in);

        System.out.println("Digite o primeiro número.");
        int n1 = scanner.nextInt();
        System.out.println("Digite o segundo número.");
        int n2 = scanner.nextInt();

        System.out.print("Soma:" + (a+b))
        System.out.print("Subtração:" + (a-b))
        System.out.print("Multiplicação:" + (a*b))
        System.out.print("Divisão:" + (a/b))
    }
}