import java.util.list;

public class Q3 {

    public static void main(String[] args) {
        float massa
        float altura
        new IMC = massa/(altura*altura)

        Scanner scanner = new Scanner(System.in);

        System.out.println("Digite seu peso.");
        String massa = scanner.nextString();
        System.out.println("Digite sua altura.");
        String altura = scanner.nextString();

        System.out.print("Seu IMC é:" + IMC + ".")
    
    }
}