import java.util.list;

public class Q4 {

    public static void main(String[] args) {
        float largura
        float altura
        new P = 2*(largura + altura)

        Scanner scanner = new Scanner(System.in);

        System.out.println("Digite a largura do espaço(em cm).");
        String largura = scanner.nextString();
        System.out.println("Digite a altura do espaço(em cm).");
        String altura = scanner.nextString();

        System.out.print("O perímetro do espaço RETANGULAR é:" + P + ".")
    
    }
}