import java.util.Scanner;

public class Q5 {

    public static void main(String[] args) {

        int precoproduto = 7;
        new valor = notas * 5;
        new total = quantidade * precoproduto;
        new troco = valorPago - total;

        Scanner scanner = new Scanner(System.in);

        System.out.println("Caixa");
        System.out.print("Quantos produtos foram comprados?");
        int quantidade = scanner.nextInt();

        System.out.println("Total da compra: R$ " + total + ".");

        System.out.print("Quantas notas de R$5 foram dadas?");
        int notas = sc.nextInt();

        System.out.println("Troco: R$ " + troco + ".");
    }
}
