import java.util.List;

public class Q3 {
    
    public static void main(String[] agrs) {
        Scanner scanner = new Scanner(System.in);

        System.out.print("Digite sua altura(em metros):");
        int altura = scanner.nextint();
        System.out.print("Digite seu peso(em kg):");
        float peso = scanner.nextfloat();

        System.out.print("Sua altura é" + altura + "m e seu peso é" + peso + "kg.")
    } 
}